### ISSUE TITLE
How to use for own game?

### ISSUE THREAD

**Issue by ajh123** [McModLauncher/modlauncher#109]
So I've got modlauncher working in my gradle, but I can't seem to start modlauncher properly.
```
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class cpw.mods.cl.ModuleClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader is in module java.base of loader 'bootstrap'; cpw.mods.cl.ModuleClassLoader is in unnamed module of loader 'app')
	at cpw.mods.modlauncher.ModuleLayerHandler.<init>(ModuleLayerHandler.java:52)
	at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:52)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at net.ddns.minersonline.HistorySurvival.Game.start(Game.java:60)
	at net.ddns.minersonline.HistorySurvival.Game.main(Game.java:328)
```

Here's my game's start method which is called by the main method
```java
    private void start(String[] args) throws IOException, ClassNotFoundException {
        Launcher.main(args); //This is Game.java:60
        ...
    }
```

**Comment by ajh123** [comment]
This is my full [code ](https://github.com/ajh123-development/HistorySurvival/tree/a29d16d717867657f6ad5a5ecdc2cbf34ca6f207)if anyone needs it

**Comment by TheCurle** [comment]
This issue tracker is not tech support, neither are we going to teach you basic Java, which is the stem issue of this.
