### ISSUE TITLE
Classes from the TransformationService JAR are not found by the classloader

### ISSUE THREAD

**Issue by sp614x** [McModLauncher/modlauncher#31]
A mod JAR with ITransformationService can be loaded from `mods` folder.
Transformers are correctly processed and the transformed classes are also loaded without problems.
However if the transformed classes reference other classes from the mod JAR then the class loading fails, because the JAR classes are not visible.

For example if `net.minecraft.util.MathHelper` is patched to reference `net.optifine.util.MathUtils`, then the class loading fails with:
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
    at cpw.mods.modlauncher.Launcher.run(Launcher.java:77)
    at cpw.mods.modlauncher.Launcher.main(Launcher.java:62)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
    at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$308/261748192.call(Unknown Source)
    at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
    ... 4 more
Caused by: java.lang.NoClassDefFoundError: net/optifine/util/MathUtils
    at net.minecraft.util.math.MathHelper.<clinit>(MathHelper.java:21)
    at net.minecraft.util.Util.func_215078_k(SourceFile:87)
    at net.minecraft.util.Util.<clinit>(SourceFile:53)
    at net.minecraft.client.main.Main.main(SourceFile:56)
    ... 11 more
Caused by: java.lang.ClassNotFoundException: net.optifine.util.MathUtils
    at java.lang.ClassLoader.findClass(ClassLoader.java:530)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:102)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 15 more
```
The class `net.optifine.util.MathUtils` is included in the mod JAR using SRG naming, so it should be loadable.

**Comment by pau101** [comment]
I had also just encountered this issue and have looked into it fairly heavily and this appears to be intentional to some extent.

Jars which are loaded for a transformation service are simply not added to the launch class loader. Which would be relatively straight forward to change with alterations to just `TransformingClassLoaderBuilder` and `TransformationServicesHandler` to add them as "special jars" which currently is only the Minecraft jar.

Now, normally jars in the mods directory get accessible by the class loader from the `ModsFolderLocator`. However, this service specifically excludes jars if they provided any transformation services, see [here](https://github.com/MinecraftForge/MinecraftForge/blob/40bdde204321a3903ec28bf20f8bc7af92df5ad9/src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/ModsFolderLocator.java#L58).

I attempted jar-in-jar as a solution, but unfortunately dependency extraction has not been re-implemented in 1.13+ yet.

**Comment by LexManos** [comment]
I am not completely sure of cpw's intentions. However I can say that it IS intentional that jars accessible outside the Transformed classloader are NOT available to things inside the classloader. This is a very basic design concept. In an attempt to avoid to classloader leakage/entanglement that we have seen in the LaunchWrapper days.

I would advise separating your transformation and runtime code into separate jars. You are correct the old jar-in-jar system is not in place. Files will not be automatically extracted into separate files on disc for you. Last I spoke with cpw about that, he said that the intend solution would just to manage the nested jars in memory. You can see how FML does it using the modjar resource path and not actually adding the jars themselves onto the classpath.

**Comment by sp614x** [comment]
The transformation service classes could be easily separated by path prefix, for example:
```
class=org.example.transformation.ExampleTransformationService
prefix=org.example.transformation.
```
The transformation classloader would only load classes with the prefix, the regular classloader would skip classes with the prefix. By default the prefix could be the package name of the transformation service.

**Comment by LexManos** [comment]
Yes, I understand how LaunchWrapper worked, it doesn't mean it was good design.
Again, things outside the transformed code should not be accessible to things inside the transformed classloader.
In [Forge](https://github.com/MinecraftForge/MinecraftForge/tree/1.14.x/src/fmllauncher) This is a completely separate jar we create. However, in your project you can set it up however you wish. You're just responsible for loading your needed classes at arms length. we do this in FML Mods by using the [ModJarURL](https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/src/fmllauncher/java/net/minecraftforge/fml/loading/ModJarURLHandler.java) In your code however, probably the simplest option would be to use your transformer to load the needed class files. As Transformers ARE called on classes that we do not load the bytecode for.

Tho, cpw would have to clarify everything. Just adding my observations.

**Comment by sp614x** [comment]
The missing classes are really going through the transformer. 
This makes it much easier, the transformer can just load them from the JAR.

**Comment by sp614x** [comment]
Loading the missing classes works now, but class loading crashes later when it tries to load super classes directly as stream, not via the transformer:
```
Class net/optifine/config/GlVersion unable to find resource null
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:77)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:62)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$308/1543043602.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	... 4 more
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.client.renderer.vertex.DefaultVertexFormats.<clinit>(DefaultVertexFormats.java:24)
	at net.minecraftforge.client.ForgeHooksClient$LightGatheringTransformer.<clinit>(ForgeHooksClient.java:564)
	at net.minecraftforge.client.ForgeHooksClient.<clinit>(ForgeHooksClient.java:607)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:319)
	at net.minecraft.client.main.Main.main(SourceFile:154)
	... 11 more
Caused by: java.lang.RuntimeException: Failed to load hierarchy member net/optifine/config/GlVersion
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:86)
	at cpw.mods.modlauncher.TransformerClassWriter.getSupers(TransformerClassWriter.java:54)
	at cpw.mods.modlauncher.TransformerClassWriter.getCommonSuperClass(TransformerClassWriter.java:102)
	at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1209)
	at org.objectweb.asm.Frame.merge(Frame.java:1293)
	at org.objectweb.asm.Frame.merge(Frame.java:1185)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1604)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1540)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:807)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:687)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:436)
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:236)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:127)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:97)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.optifine.reflect.Reflector.logEntry(Reflector.java:1460)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:140)
	... 16 more
Caused by: java.io.IOException: Class not found
	at org.objectweb.asm.ClassReader.readStream(ClassReader.java:300)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:273)
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:82)
	... 33 more
```
The problematic place: https://github.com/cpw/modlauncher/blob/master/src/main/java/cpw/mods/modlauncher/TransformerClassWriter.java#L86

The GlVersion class doesn't have a hierarchy at all, either parent or children.

**Comment by LexManos** [comment]
I'll have to have @cpw clarify on that. But potential solution would be to return object in that function if resource is null.
Computing the frames is a optional thing that just gives hints to the compiler.

**Comment by cpw** [comment]
OK @sp614x I'm gonna need some understanding of your "solution" after lex here. I was looking at ways to expose a mechanism to allow adding "something" to the classpath. But it sounds like you already did that?

**Comment by cpw** [comment]
Please review the 3.x series, should be everything you need there, to supply a class locator to your jar file.

**Comment by sp614x** [comment]
The solution was that the missing classes can be loaded via the transformer. The transformer `targets()` method now specifies both the patched MC classes and the optifine classes. So far it seems to work and loads about 20 classes, but it fails at `net.optifine.config.GlVersion`: https://pastebin.com/DBQVmSHX

It looks like `TransformerClassWriter.computeHierarchy()` is trying to load the class directly, not via the transformer and it fails.

This is tested with the 3.0.1 modlauncher. The `additionalClassesLocator()` is implemented for "net.optifine." and it is called on initialization, but the resolver method `name -> URL` is not called at all.

**Comment by cpw** [comment]
it's not called at all? Fascinating... It should be in the classloader as one of the alternative searchers.

**Comment by sp614x** [comment]
The `TransformationServiceDecorator.getOptionalClassURL` doesn't work because the `className` is separated by `/` and the prefix is separated by `.`.
The transformation service can't register package name with `/` as there is an explicit check for `.` in `TransformationServiceDecorator`.

**Comment by sp614x** [comment]
The `ITransformationService.additionalClassesLocator()` is in fact used for resource loading, it should be named `getResourceLocator()`.

**Comment by sp614x** [comment]
Loading resources from the root JAR folder is not possible as the prefix "" is not allowed.
The restrictions should be relaxed a little to make the resource loading usable.

**Comment by sp614x** [comment]
Extending the resource filters like this would be nice:
- package filter - ends with ".", checked with `startsWith()`
- file filter - path + file name, checked with `equals()`

**Comment by sp614x** [comment]
Adding a new transformer TargetType.RESOURCE would be very useful.
It would allow loading of resources which are distributed as patches of the vanilla resources.

**Comment by Technici4n** [comment]
This is not applicable as of ModLauncher 9, please open a new issue if you are still encountering problems.
