### ISSUE TITLE
Unable to transform class related to record.

### ISSUE THREAD

**Issue by ZekerZhayard** [McModLauncher/modlauncher#74]
Consider the following use case:
```java
package com.example;
public record ExampleRecord(String name) {}
```
```java
package com.example.mixin;

import com.example.ExampleRecord;
import net.minecraft.client.main.Main;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@Mixin(Main.class)
public class MixinMain {
    @Inject(method = "main", at = @At("HEAD"))
    private static void inject$main(String[] args, CallbackInfo ci) {
        try {
            ExampleRecord record = new ExampleRecord("");
        } catch (Throwable t) {}
    }
}
```

The above code will throw the following exception:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.UnsupportedOperationException: Record requires ASM8
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)
Caused by: java.lang.UnsupportedOperationException: Record requires ASM8
	at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassVisitor.visitRecordComponent(ClassVisitor.java:305)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.readRecordComponent(ClassReader.java:930)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.accept(ClassReader.java:708)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.computeHierarchyFromFile(TransformerClassWriter.java:151)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:112)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.getSupers(TransformerClassWriter.java:83)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformerClassWriter.getCommonSuperClass(TransformerClassWriter.java:63)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.Frame.merge(Frame.java:1299)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.Frame.merge(Frame.java:1197)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
	at org.objectweb.asm@9.1.0/org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
	at org.objectweb.asm.tree@9.1.0/org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769)
	at org.objectweb.asm.tree@9.1.0/org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
	at org.objectweb.asm.tree@9.1.0/org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:133)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:631)
	at java.base/java.lang.Class.forName(Class.java:543)
	at MC-BOOTSTRAP/fmlloader@1.17.1-37.0.61/net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.lambda$launchService$0(ForgeClientUserdevLaunchHandler.java:38)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	... 7 more
```

This is caused by `SuperCollectingVisitor` using ASM7 which does not support record:
https://github.com/cpw/modlauncher/blob/8569cdfcbc41cf97d7fcf94e34789072af64c0a8/src/main/java/cpw/mods/modlauncher/TransformerClassWriter.java#L168-L170

**Comment by Mumfrey** [comment]
Just FYI, Mixin does not yet support records, you should avoid using records in mixins as any special handling required is not implemented.

**Comment by ZekerZhayard** [comment]
yeah i know, but I think this issue is not related to Mixin, because even using raw ASM will cause the same issue.
modlauncher should allow developers to reference records, and I don't think that special handling of records is needed in the current use case. :
```javascript
var Opcodes = Java.type("org.objectweb.asm.Opcodes");
var InsnList = Java.type("org.objectweb.asm.tree.InsnList");
var InsnNode = Java.type("org.objectweb.asm.tree.InsnNode");
var JumpInsnNode = Java.type("org.objectweb.asm.tree.JumpInsnNode");
var LabelNode = Java.type("org.objectweb.asm.tree.LabelNode");
var LdcInsnNode = Java.type("org.objectweb.asm.tree.LdcInsnNode");
var MethodInsnNode = Java.type("org.objectweb.asm.tree.MethodInsnNode");
var TryCatchBlockNode = Java.type("org.objectweb.asm.tree.TryCatchBlockNode");
var TypeInsnNode = Java.type("org.objectweb.asm.tree.TypeInsnNode");
var VarInsnNode = Java.type("org.objectweb.asm.tree.VarInsnNode");

function initializeCoreMod() {
    return {
        "MainTransformer": {
            "target": {
                "type": "METHOD",
                "class": "net/minecraft/client/main/Main",
                "methodName": "main",
                "methodDesc": "([Ljava/lang/String;)V"
            },
            "transformer": function (mn) {
                var il = new InsnList();
                var l0 = new LabelNode(), l1 = new LabelNode(), l2 = new LabelNode(), l3 = new LabelNode();
                il.add(l0);
                il.add(new TypeInsnNode(Opcodes.NEW, "com/example/ExampleRecord"));
                il.add(new InsnNode(Opcodes.DUP));
                il.add(new LdcInsnNode(""));
                il.add(new MethodInsnNode(Opcodes.INVOKESPECIAL, "com/example/ExampleRecord", "<init>", "(Ljava/lang/String;)V", false));
                il.add(new VarInsnNode(Opcodes.ASTORE, 1));
                il.add(l1);
                il.add(new JumpInsnNode(Opcodes.GOTO, l3));
                il.add(l2);
                il.add(new VarInsnNode(Opcodes.ASTORE, 1));
                il.add(l3);
                mn.instructions.insert(il);
                mn.tryCatchBlocks.add(new TryCatchBlockNode(l0, l1, l2, "java/lang/Throwable"));
                return mn;
            }
        }
    };
}
```

**Comment by Mumfrey** [comment]
> yeah i know, but I think this issue is not related to Mixin, because even using raw ASM will cause the same issue.

I know that, which is why I prefaced my comment with "FYI". It's not a comment on whether this issue is valid or not, it was just a comment about using records in mixins being a bad idea.

**Comment by IzzelAliz** [comment]
This is rather important as 1.18 is released with records.

**Comment by ZekerZhayard** [comment]
There are at least five references to `ASM7`

https://github.com/cpw/modlauncher/blob/8569cdfcbc41cf97d7fcf94e34789072af64c0a8/src/main/java/cpw/mods/modlauncher/ClassTransformer.java#L68-L74

https://github.com/cpw/modlauncher/blob/8569cdfcbc41cf97d7fcf94e34789072af64c0a8/src/main/java/cpw/mods/modlauncher/PredicateVisitor.java#L33-L47

https://github.com/cpw/modlauncher/blob/8569cdfcbc41cf97d7fcf94e34789072af64c0a8/src/main/java/cpw/mods/modlauncher/TransformerClassWriter.java#L168-L170

**Comment by TomTheFurry** [comment]
Got linked to this issue. Is there any updates on this?

**Comment by TomTheFurry** [comment]
This is currently blocking our issue on Distant Horizons mod:
https://gitlab.com/jeseibel/minecraft-lod-mod/-/issues/139

**Comment by ZekerZhayard** [comment]
> Got linked to this issue. Is there any updates on this?

@TomTheFurry there is a dumb solution before this problem is really fixed:
that is to find the problematic class (most of them are sealed class or record) through the interruption point, then remove the sealed or record through a transformer 
```javascript

function initializeCoreMod() {
    return {
        "modlauncher#74": {
            "target": {
                "type": "CLASS",
                "name": "java/lang/constant/ConstantDesc"
            },
            "transformer": function (cn) {
                cn.permittedSubclasses = null;
                return cn;
            }
        }
    };
}
```
