### ISSUE TITLE
[NPE] Cannot invoke "joptsimple.OptionSet.valueOf(joptsimple.OptionSpec)" because "this.optionSet" is null

### ISSUE THREAD

**Issue by SizableShrimp** [McModLauncher/modlauncher#82]
766836fca64776ccd14e22c9be16c27f0a5fba57 introduced a crash that causes ModLauncher 9 to exit every time with a null pointer exception.

The stack trace on Forge 1.18.1:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "joptsimple.OptionSet.valueOf(joptsimple.OptionSpec)" because "this.optionSet" is null
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.17/cpw.mods.modlauncher.ArgumentHandler.lambda$setArgs$0(ArgumentHandler.java:46)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.17/cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.17/cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.17/cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:67)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.17/cpw.mods.modlauncher.ArgumentHandler.setArgs(ArgumentHandler.java:46)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.17/cpw.mods.modlauncher.Launcher.run(Launcher.java:85)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.17/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.17/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.17/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)
```

This issue currently affects any Forge userdev environments on 1.17 and 1.18 as ModLauncher is dynamically versioned with `9.0.+` in [MinecraftForge/EventBus](https://github.com/MinecraftForge/EventBus/blob/6d3407ccf8a8f74bc66c759cbf40f3909c918c8f/build.gradle#L102), [MinecraftForge/CoreMods](https://github.com/MinecraftForge/CoreMods/blob/303343f84d7ceccb739268b221590b357ecf1bb6/build.gradle#L67), and [FMLLoader](https://github.com/MinecraftForge/MinecraftForge/blob/72598871762a98c566689acddec539fa369ed86c/fmlloader/build.gradle#L26).

For userdev, the current workaround involves adding the following snippet to the `dependencies {}` block in `build.gradle`:
```groovy
afterEvaluate {
    minecraft('cpw.mods:modlauncher:9.0.7') {
        force = true
    }
}
```

**Comment by cpw** [comment]
Fixed by #83
